version: '3'
services:
  frontend:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    command: sh -c 'cd frontend && yarn start'
    ports:
      - 8000:3000
    tty: true
  backend:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./:/usr/src/app



